### ISSUE TITLE
I tested origins on mc 1.18.1 from version 1.3.1.4 to 1.3.1.6 and if i'm using alex's mobs mod I have some weird error I use origin where I can transform into a fox and if I crouch as a fox I get kicked from the server (this error occur only on server)

### ISSUE THREAD

**Issue by Foxsyl** [EdwinMindcraft/origins-architectury#122]
[21:15:44] [Server thread/INFO]: Foxsyl joined the game
[21:15:44] [Netty Server IO #2/ERROR]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@6dc872a (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[21:15:44] [Netty Server IO #2/ERROR]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@7cdc07d8 (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[21:15:44] [Netty Server IO #2/ERROR]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@3b5241fe (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[21:15:46] [Server thread/INFO]: Received secret request of Foxsyl (14)
[21:15:46] [Server thread/INFO]: Sent secret to Foxsyl
[21:15:55] [VoiceChatPacketProcessingThread/INFO]: Successfully authenticated player 014140b5-6891-4bd3-8cc9-29a15904c039
[21:16:08] [Server thread/ERROR]: Exception caught during firing event: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.access.MovingEntity (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.1 of loader 'TRANSFORMER' @127705e4; io.github.apace100.apoli.access.MovingEntity is in module origins@1.18.1-1.3.1.5 of loader 'TRANSFORMER' @127705e4)
        Index: 3
        Listeners:
                0: NORMAL
                1: ASM: com.github.alexthe666.citadel.server.CitadelEvents@37742986 onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                2: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@56369d19 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                3: ASM: class io.github.edwinmindcraft.apoli.common.ApoliEventHandler livingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                4: ASM: class slimeknights.tconstruct.tools.logic.ToolEvents livingWalk(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                5: ASM: class com.simibubi.create.events.CommonEvents onUpdateLivingEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                6: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem holdingExtendoGripIncreasesRange(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                7: ASM: class com.simibubi.create.content.curiosities.armor.DivingHelmetItem breatheUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                8: ASM: class com.simibubi.create.content.curiosities.armor.DivingBootsItem accellerateDescentUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                9: net.minecraftforge.eventbus.EventBus$$Lambda$3937/0x0000000801608668@6fd19d93
                10: net.minecraftforge.eventbus.EventBus$$Lambda$3937/0x0000000801608668@5aa337f1
                11: net.minecraftforge.eventbus.EventBus$$Lambda$3937/0x0000000801608668@65eb4272
                12: net.minecraftforge.eventbus.EventBus$$Lambda$3937/0x0000000801608668@4ac1a0d2
                13: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@23e3edd0 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                14: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@2a60c7bc onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                15: net.minecraftforge.eventbus.EventBus$$Lambda$3937/0x0000000801608668@291f811c
                16: ASM: squeek.appleskin.network.SyncHandler@6944bc2a onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                17: ASM: com.oitsjustjose.vtweaks.common.entity.ChallengerParticles@3b5b3087 registerEvent(Lnet/minecraftforge/event/entity/EntityEvent;)V
java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.access.MovingEntity (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.1 of loader 'TRANSFORMER' @127705e4; io.github.apace100.apoli.access.MovingEntity is in module origins@1.18.1-1.3.1.5 of loader 'TRANSFORMER' @127705e4)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.registry.condition.ApoliEntityConditions.lambda$static$7(ApoliEntityConditions.java:70)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:36)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:14)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:28)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.registry.condition.ApoliEntityConditions.lambda$static$0(ApoliEntityConditions.java:47)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$check$10(ConditionStreamConfiguration.java:40)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$andCodec$7(ConditionStreamConfiguration.java:31)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.check(ConditionStreamConfiguration.java:40)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:16)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:9)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:28)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.registry.action.ApoliEntityActions.lambda$static$1(ApoliEntityActions.java:29)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.action.meta.IfElseConfiguration.execute(IfElseConfiguration.java:24)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:15)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:8)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityAction.execute(ConfiguredEntityAction.java:24)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.registry.action.ApoliEntityActions.lambda$static$0(ApoliEntityActions.java:28)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.action.meta.StreamConfiguration.lambda$execute$4(StreamConfiguration.java:48)
        at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.action.meta.StreamConfiguration.execute(StreamConfiguration.java:48)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:15)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:8)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityAction.execute(ConfiguredEntityAction.java:24)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.power.ActionOverTimePower.tick(ActionOverTimePower.java:30)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:132)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:137)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.component.PowerContainer.serverTick(PowerContainer.java:189)
        at TRANSFORMER/forge@39.1.2/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150)
        at TRANSFORMER/origins@1.18.1-1.3.1.5/io.github.edwinmindcraft.apoli.common.ApoliEventHandler.livingTick(ApoliEventHandler.java:90)
        at net.minecraftforge.eventbus.ASMEventHandler_326_ApoliEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@39.1.2/net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:289)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2210)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.Connection.m_129483_(Connection.java:233)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:833)

[21:16:09] [Server thread/WARN]: Failed to handle packet for /26.217.21.51:63249
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.access.MovingEntity (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.1 of loader 'TRANSFORMER' @127705e4; io.github.apace100.apoli.access.MovingEntity is in module origins@1.18.1-1.3.1.5 of loader 'TRANSFORMER' @127705e4)
        at io.github.edwinmindcraft.apoli.common.registry.condition.ApoliEntityConditions.lambda$static$7(ApoliEntityConditions.java:70) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:36) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:14) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:28) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.registry.condition.ApoliEntityConditions.lambda$static$0(ApoliEntityConditions.java:47) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$check$10(ConditionStreamConfiguration.java:40) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$andCodec$7(ConditionStreamConfiguration.java:31) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.check(ConditionStreamConfiguration.java:40) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:16) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:9) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:28) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.registry.action.ApoliEntityActions.lambda$static$1(ApoliEntityActions.java:29) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.action.meta.IfElseConfiguration.execute(IfElseConfiguration.java:24) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:15) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:8) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityAction.execute(ConfiguredEntityAction.java:24) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.registry.action.ApoliEntityActions.lambda$static$0(ApoliEntityActions.java:28) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.action.meta.StreamConfiguration.lambda$execute$4(StreamConfiguration.java:48) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%2321!/:?]
        at io.github.edwinmindcraft.apoli.common.action.meta.StreamConfiguration.execute(StreamConfiguration.java:48) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:15) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:8) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityAction.execute(ConfiguredEntityAction.java:24) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.power.ActionOverTimePower.tick(ActionOverTimePower.java:30) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:132) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:137) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at io.github.edwinmindcraft.apoli.common.component.PowerContainer.serverTick(PowerContainer.java:189) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.1-39.1.2-universal.jar%2397!/:?]
        at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.livingTick(ApoliEventHandler.java:90) ~[Origins-1.18.1-1.3.1.6-unified.jar%2373!/:1.18.1-1.3.1.6]
        at net.minecraftforge.eventbus.ASMEventHandler_326_ApoliEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:289) ~[forge-1.18.1-39.1.2-universal.jar%2397!/:?]
        at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2210) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.1-20211210.034407-srg.jar%2393!/:?]
        ... 9 more
[21:16:09] [Server thread/INFO]: Foxsyl lost connection: Internal server error
[21:16:09] [Server thread/INFO]: Foxsyl left the game
[21:16:09] [Server thread/INFO]: Disconnecting client Foxsyl

**Comment by killinmesmols** [comment]
i am having the same issue

**Comment by Foxsyl** [comment]
Version for minecraft 1.18.1 of this mod 1.3.1.9 fix this error
