### ISSUE TITLE
Hosted on aternos just keeps crashing 

### ISSUE THREAD

**Issue by LunarwareDeveloper** [EdwinMindcraft/origins-architectury#223]
Apperantly im missing 3 mods called minecraft....... The most common word in mods for minecraft.
`<html>
<body>

---- Minecraft Crash Report ----
--
2 | // Uh... Did I do that?
3 |  
4 | Time: 2022-08-06 08:44:15
5 | Description: Mod loading error has occurred
6 |  
7 | java.lang.Exception: Mod Loading has failed
8 | at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
9 | at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
10 | at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.1-20220727.212338-srg.jar%23113!/:?] {re:classloading}
11 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
12 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
13 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
14 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
15 | at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.1-42.0.9.jar%2367!/:?] {}
16 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
17 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
18 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
19 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
20 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
21 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
22 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
23 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
24 |  
25 |  
26 | A detailed walkthrough of the error, its code path and all known details is as follows:
27 | ---------------------------------------------------------------------------------------
28 |  
29 | -- Head --
30 | Thread: main
31 | Stacktrace:
32 | at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
33 | -- MOD origins --
34 | Details:
35 | Mod File: /server/mods/origins-forge-1.19-1.5.0.4-fatjar.jar
36 | Failure message: Mod origins requires minecraft 1.19
37 | Currently, minecraft is 1.19.1
38 | Mod Version: 1.19-1.5.0.4
39 | Mod Issue URL: https://github.com/EdwinMindcraft/origins-architectury/issues
40 | Exception message: MISSING EXCEPTION MESSAGE
41 | Stacktrace:
42 | at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
43 | at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
44 | at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:56) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
45 | at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
46 | at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.1-20220727.212338-srg.jar%23113!/:?] {re:classloading}
47 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
48 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
49 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
50 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
51 | at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.1-42.0.9.jar%2367!/:?] {}
52 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
53 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
54 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
55 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
56 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
57 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
58 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
59 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
60 |  
61 |  
62 | -- MOD apoli --
63 | Details:
64 | Mod File: /server/mods/origins-forge-1.19-1.5.0.4-fatjar.jar#110!/META-INF/jarjar/apoli-forge-1.19-2.3.4.2.jar
65 | Failure message: Mod apoli requires minecraft 1.19
66 | Currently, minecraft is 1.19.1
67 | Mod Version: 1.19-2.3.4.2
68 | Mod Issue URL: https://github.com/EdwinMindcraft/apoli/issues
69 | Exception message: MISSING EXCEPTION MESSAGE

</body>
</html>---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: [2](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L2)022-08-06 08:44:15
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.1-42.0.9-universal.jar%2[3](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L3)118!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.1-[4](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L4)2.0.9-universal.jar%23118!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.1-20220727.212338-srg.jar%23113!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:[5](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L5)[6](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L6)8) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.1-42.0.9.jar%236[7](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L7)!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.[8](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L8).jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.1[9](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L9).1-42.0.9-universal.jar%23118!/:?] {re:classloading}
-- MOD origins --
Details:
	Mod File: /server/mods/origins-forge-1.19-1.5.0.4-fatjar.jar
	Failure message: Mod origins requires minecraft 1.19
		Currently, minecraft is 1.19.1
	Mod Version: 1.19-1.5.0.4
	Mod Issue URL: https://github.com/EdwinMindcraft/origins-architectury/issues
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:56) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.1-42.0.9-universal.jar%23118!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.1-20220727.212338-srg.jar%23113!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.1-42.0.9.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-[10](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L10).0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- MOD apoli --
Details:
	Mod File: /server/mods/origins-forge-1.19-1.5.0.4-fatjar.jar#[11](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L11)0!/META-INF/jarjar/apoli-forge-1.[19](https://aternos.org/files/crash-reports/crash-2022-08-06_08.44.15-fml.txt#L19)-2.3.4.2.jar
	Failure message: Mod apoli requires minecraft 1.19
		Currently, minecraft is 1.19.1
	Mod Version: 1.19-2.3.4.2
	Mod Issue URL: https://github.com/EdwinMindcraft/apoli/issues
	Exception message: MISSING EXCEPTION MESSAGE`

**Comment by EdwinMindcraft** [comment]
Last the last 5 lines of the issue tell you exactly what's going on.
