### ISSUE TITLE
1.18.2 apex server disconnects and cant rejoin after picking origin

### ISSUE THREAD

**Issue by simplysimps** [EdwinMindcraft/origins-architectury#226]
[08Aug2022 22:19:36.738] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /73.37.117.30:57022
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @1cd43562; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.0 of loader 'TRANSFORMER' @1cd43562)
	at io.github.edwinmindcraft.apoli.common.registry.condition.ApoliEntityConditions.lambda$static$1(ApoliEntityConditions.java:59) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:37) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:13) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$check$10(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$orCodec$9(ConditionStreamConfiguration.java:37) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.check(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:15) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:8) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.lambda$isActive$6(PowerFactory.java:196) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.isActive(PowerFactory.java:196) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.isActive(ConfiguredPower.java:86) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.power.DamageOverTimePower.tick(DamageOverTimePower.java:36) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:160) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:165) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at io.github.edwinmindcraft.apoli.common.component.PowerContainer.serverTick(PowerContainer.java:191) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.73-universal.jar%23157!/:?]
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.livingTick(ApoliEventHandler.java:114) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23121%23162!/:1.18.2-2.3.4.0]
	at net.minecraftforge.eventbus.ASMEventHandler_144_ApoliEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) ~[forge-1.18.2-40.1.73-universal.jar%23157!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%23152!/:?]
	... 9 more

**Comment by EdwinMindcraft** [comment]
Will be fixed when forge's JiJ is fixed.
