### ISSUE TITLE
1.18.2 abilities crashing

### ISSUE THREAD

**Issue by MarceloHallow** [EdwinMindcraft/origins-architectury#233]
When i try to open a map with only origins and the mod requirements,work all origins but the abilities like phantomize and teleport crash my map and show error code -1,idk why i tried many ways,installing again,changing the forge version,and still doesnt work.

**Comment by EdwinMindcraft** [comment]
I can't diagnose anything without a crash report.

**Comment by MarceloHallow** [comment]
oh sorry,here is the crash report

---- Minecraft Crash Report ----
// Don't do that.

Time: 18/08/2022 16:11
Description: Ticking player

java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @1192b58e; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.1 of loader 'TRANSFORMER' @1192b58e)
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.isExposedToSun(SimpleEntityCondition.java:25) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:37) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:13) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$check$10(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$andCodec$7(ConditionStreamConfiguration.java:33) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.check(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:15) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:8) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.lambda$isActive$6(PowerFactory.java:196) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:mixin,re:classloading}
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?] {}
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.isActive(PowerFactory.java:196) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.canTick(PowerFactory.java:150) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:154) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:165) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.component.PowerContainer.serverTick(PowerContainer.java:191) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.73-universal.jar%2363!/:?] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.livingTick(ApoliEventHandler.java:114) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_69_ApoliEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) ~[forge-1.18.2-40.1.73-universal.jar%2363!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:APP:tlskincape-mixins.json:MixinPlayer,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.isExposedToSun(SimpleEntityCondition.java:25) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:37) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.SimpleEntityCondition.check(SimpleEntityCondition.java:13) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$check$10(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.lambda$andCodec$7(ConditionStreamConfiguration.java:33) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.meta.ConditionStreamConfiguration.check(ConditionStreamConfiguration.java:42) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:15) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.entity.DelegatedEntityCondition.check(DelegatedEntityCondition.java:8) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:35) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:43) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.lambda$isActive$6(PowerFactory.java:196) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:mixin,re:classloading}
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?] {}
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?] {}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.isActive(PowerFactory.java:196) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.canTick(PowerFactory.java:150) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:154) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.tick(ConfiguredPower.java:165) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.component.PowerContainer.serverTick(PowerContainer.java:191) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.73-universal.jar%2363!/:?] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.livingTick(ApoliEventHandler.java:114) ~[origins-forge-1.18.2-1.5.0.2-fatjar.jar%2356%2369!/:1.18.2-2.3.4.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_69_ApoliEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) ~[forge-1.18.2-40.1.73-universal.jar%2363!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:APP:tlskincape-mixins.json:MixinPlayer,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 986
	Entity Name: Marcelo_Hallow
	Entity's Exact location: -136.63, 64.00, -108.74
	Entity's Block location: World: (-137,64,-109), Section: (at 7,0,3 in -9,4,-7; chunk contains blocks -144,-64,-112 to -129,319,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 771313272 bytes (735 MiB) / 1845493760 bytes (1760 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2,80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1338
	Graphics card #1 name: NVIDIA GeForce MX330
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048,00
	Graphics card #1 deviceId: 0x1d16
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1272
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18538,79
	Virtual memory used (MB): 15322,38
	Swap memory total (MB): 2432,00
	Swap memory used (MB): 60,77
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Marcelo_Hallow'/986, l='ServerLevel[Novo mundo]', x=-136.63, y=64.00, z=-108.74]]
	Data Packs: vanilla, mod:configured (incompatible), mod:calio (incompatible), mod:caelus (incompatible), mod:forge, mod:apoli (incompatible), mod:tlskincape (incompatible), mod:origins (incompatible), mod:additionalentityattributes, mod:catalogue (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		calio-forge-1.18.2-1.6.0.0.jar                    |Calio                         |calio                         |1.18.2-1.6.0.0      |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.73-universal.jar                |Forge                         |forge                         |40.1.73             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		apoli-forge-1.18.2-2.3.4.1.jar                    |Apoli                         |apoli                         |1.18.2-2.3.4.1      |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.18_1.18.2-1.25.jar           |TLSkinCape                    |tlskincape                    |1.25                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		origins-forge-1.18.2-1.5.0.2-fatjar.jar           |Origins                       |origins                       |1.18.2-1.5.0.2      |DONE      |Manifest: NOSIGNATURE
		Forge-1.0.1-1.18.2.jar                            |Additional Entity Attributes  |additionalentityattributes    |1.0.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.2-1.18.2.jar                        |Catalogue                     |catalogue                     |1.6.2               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 9795283c-a032-491d-841a-0a70db7d3c49
	FML: 40.1
	Forge: net.minecraftforge:40.1.73
