### ISSUE TITLE
1.18.2 Ticking Entity Crash when Loading New World After Picking Origins (Heavily Modded)

### ISSUE THREAD

**Issue by Dawnbreezie** [EdwinMindcraft/origins-architectury#256]
Funnily enough, Origins Forge used to work fine in my collection of 1.18.2 mods up until I updated some of said mods. Recently, I've been getting crashes whenever I load into a new world. I have MCARe, so the Gender Selection Screen and the Character Creation Screen load first. I experience no problems with them.

After I'm done coloring the hair and eyes just right and all that jazz, the Origins Selection Screen pops up, and I definitely have no problems with the selection screen either. It's only after I pick my origin (I Main Merling) that I am shown the world, which immediately freezes the game for a moment, and then Minecraft crashes with an -1 Exit Code.

Looking at the top of the crash report PolyMC gave me, this is the supposed answer to the problem that I have no capability of fully decoding (for my brain is very smooth):

_Description: Ticking entity
java.lang.ClassCastException: class net.minecraft.client.player.LocalPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.client.player.LocalPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @7ecb9e17; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.0 of loader 'TRANSFORMER' @7ecb9e17)
at io.github.edwinmindcraft.origins.common.OriginsEventHandler.onPlayerTickEnd(OriginsEventHandler.java:193) ~[origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar%23176!/:1.18.2-1.5.0.1] {re:classloading}
at net.minecraftforge.eventbus.ASMEventHandler_259_OriginsEventHandler_onPlayerTickEnd_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}_

Knowing my luck it's probably something really stupid caused by my own negligence that's also easily fixable. But ultimately I have no idea what's going on here, considering it's worked just fine before? Who knows what could be causing it. I was thinking MCARe but it could be caused by a number of the mods I have on here, heck, maybe even caused by something PolyMC did. I know Origins is causing the crashes for a fact because when I take it out, it doesn't implode on itself after I dress myself up in the MCARe character creation screen.
Just looking at the code, I THINK there's some sort of version incompatibility with two different Apolis, but I don't know why and how that would even happen.

For anyone that offers to aid me, I greatly appreciate your time and effort. I will freely provide more details in the crash log, along with my list of mods I am trying to get to run with origins if doing so would help in detecting the issue. I'll try to look into the issue myself as well, and if I figure out anything more I'll let y'all know. Sorry for the bother! ^v^'

**Comment by SteelThundrShoc** [comment]
https://github.com/EdwinMindcraft/origins-architectury/issues/222
This might help??
