### ISSUE TITLE
Enderian Primary Ability Crash

### ISSUE THREAD

**Issue by Nitrominous** [EdwinMindcraft/origins-architectury#28]
This happened while using Forge 1.16.5, and the 1.16.5 versions of Origins (Forge), Architectury API (Forge), Caelus API (Forge), and Cloth Config API (Forge). Whenever I use my primary ability for the Enderian, which is the ender pearl, my game freezes then instantly crashes. This only happens with the Enderian, and I can play all of the other origins just fine. When I check the crash log, it says it was caused by a ticking entity. If it helps, I am on MacOS, and using the latest version of all of the mods. I only have those four mods, and nothing else. It doesn't happen when I use the fabric version of the mod.

(Down here I put stuff I think could be important)

Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraftforge.event.ForgeEventFactory.onEnderPearlLand(Lnet/minecraft/entity/player/ServerPlayerEntity;DDDLnet/minecraft/entity/item/EnderPearlEntity;F)Lnet/minecraftforge/event/entity/living/EntityTeleportEvent$EnderPearl;
	at io.github.apace100.origins.entity.forge.EnderianPearlEntityImpl.fireTeleportationEvent(EnderianPearlEntityImpl.java:14) ~[?:?] {re:classloading}
	at io.github.apace100.origins.entity.EnderianPearlEntity.fireTeleportationEvent(EnderianPearlEntity.java) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:origins.forge.mixins.json:EnderianPearlEntityMixin,pl:mixin:A}
	at io.github.apace100.origins.entity.EnderianPearlEntity.func_70227_a(EnderianPearlEntity.java:75) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:origins.forge.mixins.json:EnderianPearlEntityMixin,pl:mixin:A}
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:67) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.item.EnderPearlEntity.func_70071_h_(EnderPearlEntity.java:91) ~[?:?] {re:mixin,re:classloading}
	at io.github.apace100.origins.entity.EnderianPearlEntity.func_70071_h_(EnderianPearlEntity.java:100) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:origins.forge.mixins.json:EnderianPearlEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {} 

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.apace100.origins.entity.forge.EnderianPearlEntityImpl.fireTeleportationEvent(EnderianPearlEntityImpl.java:14) ~[?:?] {re:classloading}
	at io.github.apace100.origins.entity.EnderianPearlEntity.fireTeleportationEvent(EnderianPearlEntity.java) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:origins.forge.mixins.json:EnderianPearlEntityMixin,pl:mixin:A}
	at io.github.apace100.origins.entity.EnderianPearlEntity.func_70227_a(EnderianPearlEntity.java:75) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:origins.forge.mixins.json:EnderianPearlEntityMixin,pl:mixin:A}
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:67) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.item.EnderPearlEntity.func_70071_h_(EnderPearlEntity.java:91) ~[?:?] {re:mixin,re:classloading}
	at io.github.apace100.origins.entity.EnderianPearlEntity.func_70071_h_(EnderianPearlEntity.java:100) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:origins.forge.mixins.json:EnderianPearlEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,re:mixin}
-- Entity being ticked --
Details:
	Entity Type: origins:enderian_pearl (io.github.apace100.origins.entity.EnderianPearlEntity)
	Entity ID: 1425
	Entity Name: entity.origins.enderian_pearl
	Entity's Exact location: -10.10, 64.43, 126.10
	Entity's Block location: World: (-11,64,126), Chunk: (at 5,4,14 in -1,7; contains blocks -16,0,112 to -1,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 1.16, -0.73, -0.59
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,re:mixin}
<img width="2560" alt="Screen Shot 2021-06-11 at 8 32 13 AM" src="https://user-

Right before it crashed -
<img width="2560" alt="Screen Shot 2021-06-11 at 8 32 13 AM" src="https://user-images.githubusercontent.com/85728127/121712204-57149480-ca90-11eb-835f-70a67b214b7c.png">

Mod List:
<img width="527" alt="Screen Shot 2021-06-11 at 8 35 41 AM" src="https://user-images.githubusercontent.com/85728127/121712048-1ddc2480-ca90-11eb-8130-b9625064b788.png">

**Comment by EdwinMindcraft** [comment]
Update forge to at least 36.1.3.
I recommend using the latest version. Recommended builds are always older than they should realistically be.
