### ISSUE TITLE
Corrupted Player data from disconnecting/crashing in the ground

### ISSUE THREAD

**Issue by n0valey** [EdwinMindcraft/origins-architectury#294]
So me and my friends are playing on a modded minecraft server, we have encountered the same data corrupting bug twice, triggered by the same actions.
It has happened both times, with the main two offending mods being Origins for forge(Your port of the origins fabric mod) and Apotheosis. Where a friend of mine, who has been playing as a phantom, crashes in the ground due to hitting an apotheosis boss from within the ground with his apotheosis sword. Of course the crash itself isn't a problem for you since it isn't your mod. BUT whenever my friend crashes from that bug, thus delogging in the ground, his player data has been corrupted, and I haven't found any solution outside of manually changing his nbt data. It has happened twice during the same circumstance and it has corrupted his player data twice, which I think is a bad problem if it causes a player inventory reset at best and world reset at worst. 
I do recognize this is a port, so I don't know if I should be posting this issue to your mod or to the original origins mod maker. I am starting with you since I am using your port.
If there is anything I can grab to help this being fixed, please let me know! 
The error is being shown as "internal server error occured" and refuses to let him log back in until i wipe his player data.

**Comment by n0valey** [comment]
Server thread/[WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /99.242.209.236:53466
22.02 22:02:44 [Server] [INFO] net.minecraft.ReportedException: Ticking player
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,re:classloading,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) [?:?] {re:mixin}
22.02 22:02:44 [Server] [INFO] Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_5647_()" because "p_36169_" is null
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.player.Player.m_7099_(Player.java:881) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:additionalentityattributes.mixins.json:common.DigSpeedMixin,pl:mixin:APP:additionalentityattributes.mixins.json:common.PlayerEntityMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:apoli.mixins.json:PlayerEntityMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:APP:origins_classes.mixins.json:common.minecraft.PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:domesticationinnovation.mixins.json:PlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.m_7099_(ServerPlayer.java:677) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.sweenus.simplyswords.util.HelperMethods.checkFriendlyFire(HelperMethods.java:48) ~[simplyswords-forge-1.40-1.19.2.jar%23213!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.sweenus.simplyswords.effect.WildfireEffect.m_6742_(WildfireEffect.java:35) ~[simplyswords-forge-1.40-1.19.2.jar%23213!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:187) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,xf:fml:forge:potion,pl:mixin:APP:apoli.mixins.json:StatusEffectInstanceMixin,pl:mixin:APP:bookshelf.common.mixins.json:effect.AccessorMobEffectInstance,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:160) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,xf:fml:forge:potion,pl:mixin:APP:apoli.mixins.json:StatusEffectInstanceMixin,pl:mixin:APP:bookshelf.common.mixins.json:effect.AccessorMobEffectInstance,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.LivingEntity.m_21217_(LivingEntity.java:745) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:oriacs.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:origins_classes.mixins.json:accessor.minecraft.LivingEntityAccessor,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:418) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:oriacs.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:origins_classes.mixins.json:accessor.minecraft.LivingEntityAccessor,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.Entity.m_8119_(Entity.java:417) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:apoli:apoli_prevent_suffocation,re:classloading,pl:accesstransformer:B,xf:fml:apoli:apoli_prevent_suffocation,pl:mixin:APP:oriacs.mixins.json:EntityMixin,pl:mixin:APP:apoli.mixins.json:EntityAccessor,pl:mixin:APP:apoli.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinEntity,pl:mixin:APP:origins.mixins.json:SelectionInvulnerabilityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:block.hopper.EntityAccessor,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:EntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2252) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:oriacs.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:origins_classes.mixins.json:accessor.minecraft.LivingEntityAccessor,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:additionalentityattributes.mixins.json:common.DigSpeedMixin,pl:mixin:APP:additionalentityattributes.mixins.json:common.PlayerEntityMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:apoli.mixins.json:PlayerEntityMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:APP:origins_classes.mixins.json:common.minecraft.PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:domesticationinnovation.mixins.json:PlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] ... 9 more
22.02 22:02:44 [Disconnect] User Zeithelik has disconnected, reason: Internal server error
22.02 22:02:44 [Server] Server thread/[INFO] [minecraft/MinecraftServer]: Zeithelik left the game

that is what the logs said, maybe its because of my inexperience but i can't make out what exactly went wrong here

**Comment by n0valey** [comment]
Upon further investigation, it seems like origins had nothing to do with it, it was a conflict between two different mods. As he crashed out of the ground and it still corrupted his data. Sorry!
