### ISSUE TITLE
Using Origins/Origins Classes/Bucolic Origins

### ISSUE THREAD

**Issue by Kiwicast** [EdwinMindcraft/origins-architectury#303]
When using the these mods, for some reason when someone dies using their power their player data becomes corrupt then I get the following error in my console:

[04:37:49] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
net.minecraft.ReportedException: Loading entity NBT
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1628) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,xf:fml:apoli:apoli_prevent_suffocation,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,xf:fml:apoli:apoli_prevent_suffocation,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,xf:fml:apoli:apoli_prevent_suffocation,pl:mixin:APP:apoli.mixins.json:EntityAccessor,pl:mixin:APP:apoli.mixins.json:EntityMixin,pl:mixin:APP:carryon.mixins.json:EntityMixin,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:origins.mixins.json:SelectionInvulnerabilityMixin,pl:mixin:APP:sliceanddice.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:step_height.EntityMixin,pl:mixin:APP:blueprint.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin,pl:mixin:A}
        at net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:56) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:classloading}
        at net.minecraft.server.players.PlayerList.m_11224_(PlayerList.java:309) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,re:classloading,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,pl:mixin:A}
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,re:classloading,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.DedicatedServerMixin,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.IllegalStateException: Capability has not been initialised
        at me.lucko.luckperms.forge.capabilities.UserCapabilityImpl.assertInitialised(UserCapabilityImpl.java:108) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
        at me.lucko.luckperms.forge.capabilities.UserCapabilityImpl.checkPermission(UserCapabilityImpl.java:114) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
        at me.lucko.luckperms.forge.util.BrigadierInjector$InjectedPermissionRequirement.test(BrigadierInjector.java:146) ~[?:?] {}
        at me.lucko.luckperms.forge.util.BrigadierInjector$InjectedPermissionRequirement.test(BrigadierInjector.java:131) ~[?:?] {}
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:65) ~[brigadier-1.0.18.jar%2374!/:?] {}
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:358) ~[brigadier-1.0.18.jar%2374!/:?] {}
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348) ~[brigadier-1.0.18.jar%2374!/:?] {}
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:316) ~[brigadier-1.0.18.jar%2374!/:?] {}
        at net.minecraft.commands.Commands.m_230957_(Commands.java:220) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:classloading}
        at io.github.edwinmindcraft.apoli.common.action.configuration.CommandConfiguration.executeAt(CommandConfiguration.java:47) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.common.action.configuration.CommandConfiguration.execute(CommandConfiguration.java:53) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.common.action.entity.ExecuteCommandEntityAction.execute(ExecuteCommandEntityAction.java:15) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.common.action.entity.ExecuteCommandEntityAction.execute(ExecuteCommandEntityAction.java:7) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityAction.execute(ConfiguredEntityAction.java:43) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.common.action.meta.ExecuteMultipleConfiguration.lambda$execute$1(ExecuteMultipleConfiguration.java:21) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?] {}
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
        at io.github.edwinmindcraft.apoli.common.action.meta.ExecuteMultipleConfiguration.execute(ExecuteMultipleConfiguration.java:21) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:15) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.common.action.entity.DelegatedEntityAction.execute(DelegatedEntityAction.java:8) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityAction.execute(ConfiguredEntityAction.java:43) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityAction.execute(ConfiguredEntityAction.java:35) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.apace100.origins.power.OriginsCallbackPower.onAdded(OriginsCallbackPower.java:27) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:classloading}
        at io.github.apace100.origins.power.OriginsCallbackPower.onAdded(OriginsCallbackPower.java:10) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:classloading}
        at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.onAdded(PowerFactory.java:184) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:mixin,re:classloading}
        at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.onAdded(ConfiguredPower.java:123) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:mixin,re:classloading}
        at io.github.edwinmindcraft.apoli.common.component.PowerContainer.addPower(PowerContainer.java:118) ~[apoli-forge-1.19.2-2.3.4.4.jar%23354!/:1.19.2-2.3.4.4] {re:classloading}
        at io.github.edwinmindcraft.origins.common.capabilities.OriginContainer.lambda$grantPowers$1(OriginContainer.java:99) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:classloading}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at io.github.edwinmindcraft.origins.common.capabilities.OriginContainer.grantPowers(OriginContainer.java:97) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:classloading}
        at io.github.edwinmindcraft.origins.common.capabilities.OriginContainer.lambda$setOrigin$0(OriginContainer.java:79) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:classloading}
        at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.2-43.2.4-universal.jar%23332!/:?] {re:mixin,re:classloading,pl:mixin:APP:phosphophyllite.mixins.json:LazyOptionalMixin,pl:mixin:A}
        at io.github.edwinmindcraft.origins.common.capabilities.OriginContainer.setOrigin(OriginContainer.java:78) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:classloading}
        at io.github.edwinmindcraft.origins.api.capabilities.IOriginContainer.setOrigin(IOriginContainer.java:54) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:mixin,re:classloading}
        at io.github.edwinmindcraft.origins.common.capabilities.OriginContainer.deserializeNBT(OriginContainer.java:342) ~[origins-forge-1.19.2-1.5.0.6-all.jar%23284!/:1.19.2-1.5.0.6] {re:classloading}
        at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:127) ~[forge-1.19.2-43.2.4-universal.jar%23332!/:?] {re:classloading}
        at net.minecraftforge.common.capabilities.CapabilityProvider.deserializeCaps(CapabilityProvider.java:148) ~[forge-1.19.2-43.2.4-universal.jar%23332!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1602) ~[server-1.19.2-20220805.130853-srg.jar%23327!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,xf:fml:apoli:apoli_prevent_suffocation,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,xf:fml:apoli:apoli_prevent_suffocation,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,xf:fml:apoli:apoli_prevent_suffocation,pl:mixin:APP:apoli.mixins.json:EntityAccessor,pl:mixin:APP:apoli.mixins.json:EntityMixin,pl:mixin:APP:carryon.mixins.json:EntityMixin,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:origins.mixins.json:SelectionInvulnerabilityMixin,pl:mixin:APP:sliceanddice.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:step_height.EntityMixin,pl:mixin:APP:blueprint.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin,pl:mixin:A}
        ... 14 more

**Comment by EdwinMindcraft** [comment]
LuckPerms is causing issues by not initializing properly.
