### ISSUE TITLE
Unable to join singleplayer world due to this error

### ISSUE THREAD

**Issue by norfaremc** [EdwinMindcraft/origins-architectury#350]
We have run into this error HUNDREDS of times. We thought with the new update it would fix itself. 
I had a singleplayer world used strictly for testing for our modpack. 
We updated to the latest version of Origins, and still received the following error when I attempted to load into my singleplayer test world:
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/133526827/5b8bafc4-3f6d-45d4-80d5-ef220c473d7b)

Upon returning to "server list"... my singleplayer world was gone. This is the screen I returned to:
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/133526827/4861d540-36b4-4d77-84e5-5638d074bd3c)

While this isn't a big issue for me, as this was simply a test world, I worry for our singleplayers who download our modpack, run into this issue only to lose any and all progress they've ever made of their world. Desperately hoping for a fix ASAP.

The following was in our changelog:
[11:05:23] [Worker-Main9/WARN]: Failed to read C:\Users\Norfare\curseforge\minecraft\Instances\Medieval Norfare\saves\test world
java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229) ~[?:?]
	at sun.nio.ch.FileLockTable.add(FileLockTable.java:123) ~[?:?]
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321) ~[?:?]
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1191) ~[?:?]
	at net.minecraft.util.DirectoryLock.m_13642_(DirectoryLock.java:83) ~[client-1.19.2-20220805.130853-srg.jar%23713!/:?]
	at net.minecraft.world.level.storage.LevelStorageSource.lambda$loadLevelSummaries$4(LevelStorageSource.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23713!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by norfaremc** [comment]
At this point I cannot open a singleplayer world, no matter what. I've tried 4 times now and I just get this error every single time.
