### ISSUE TITLE
Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_entity_condition] was missing

### ISSUE THREAD

**Issue by QuantumXenon** [EdwinMindcraft/origins-architectury#366]
Versions: Origins (Forge) 1.10.0.1, Forge 47.1.0

Sometimes (but not every time), when I try to generate a new world, the game fails and shoes the error `Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_entity_condition] was missing`.

Here is the part causing the issue from the logs:
```
[Netty Server IO #1/ERROR] [net.minecraft.network.Connection/]: Received class net.minecraft.network.protocol.login.ClientboundLoginDisconnectPacket that couldn't be processed
java.lang.ClassCastException: class net.minecraft.server.network.ServerLoginPacketListenerImpl cannot be cast to class net.minecraft.network.protocol.login.ClientLoginPacketListener (net.minecraft.server.network.ServerLoginPacketListenerImpl and net.minecraft.network.protocol.login.ClientLoginPacketListener are in module minecraft@1.20.1 of loader 'TRANSFORMER' @5d3b58ca)
	at net.minecraft.network.protocol.login.ClientboundLoginDisconnectPacket.m_5797_(ClientboundLoginDisconnectPacket.java:7) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at net.minecraft.network.Connection.m_129517_(Connection.java:174) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:159) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:50) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Aceofdragonsally** [comment]
Having a similar issue where the game cant find entity attributes
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/12709836/latest.log)

**Comment by ChrysanthCow** [comment]
> Having a similar issue where the game cant find entity attributes [latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/12709836/latest.log)

This is not related to Origins Forge, but if you want help with looking for this. `minecraft:generic.flying_speed` is not a proper attribute in vanilla.

**Comment by ChrysanthCow** [comment]
I'm unable to replicate this with purely the base Origins, but I'm going to try downloading a larger Origins pack (Origins++, ik you're the maintainer of it, and you're probably reporting this based on that) to see if that yields different results.

**Comment by ChrysanthCow** [comment]
Confirmed fixed for next update alongside https://github.com/EdwinMindcraft/origins-architectury/issues/365.

**Comment by Xplodin** [comment]
Getting this error on 1.20.1 
https://gist.github.com/Xplodin/964f984bdc384f3918ea8b418324ba9d
origins: 1.10.0.5 forge: 47.2.19
